### ISSUE TITLE
How can I add custum data to the database?

### ISSUE THREAD

**Issue by yangmqglobe** [bio-ontology-research-group/phenotype-reactor#16]
I was trying to setup my own service and add some custom data into the database, is this possible and how can I achive this?

**Comment by leechuck** [comment]
You can add your own data to https://bio2vec.cbrc.kaust.edu.sa/ and use the API for similarity search. We don't currently have a way for users to add data to the phenotype reactor themselves, but if you have a dataset that is freely available, we would be happy to include it, just check with @aliraza995 who can add the data.
